# Generated by Django 4.2.4 on 2023-09-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers_channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
