# Generated by Django 4.2.4 on 2023-09-17 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers_channels', '0002_channel_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='users',
            field=models.ManyToManyField(related_name='servers', to=settings.AUTH_USER_MODEL),
        ),
    ]
