# Generated by Django 4.2.4 on 2023-09-17 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers_channels', '0003_server_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='users',
        ),
    ]
