# Generated by Django 4.2.4 on 2023-09-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers_channels', '0004_remove_server_users'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='servers',
            field=models.ManyToManyField(related_name='user_profiles', to='servers_channels.server'),
        ),
    ]
